x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_postgis'
    container_name: prge-2025-postgis-${ENV_NAME}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-prge-2025-data:/var/lib/postgresql/data

volumes:
  postgis-prge-2025-data: