x-enviroment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_DB}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_DB}
services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_postgis'
    container_name: 'prge_2025_postgis'
    environment:
      - *env-postgres-user
      - *env-postgres-password
      - *env-postgres-db
    ports:
      - 5444:5432
    volumes:
      - postgis-prge-2025-data:/var/lib/postgresql/data

volumes:
  postgis-prge-2025-data: